FROM rocker/tidyverse:latest
#Author: simon@mims.ai
#Date created: June 22th, 2020

RUN install2.r mgcv

ADD data/ somnibus/data/
ADD R/ /somnibus/R/

ENV TZ=America/Montreal


# Set default working path
WORKDIR /outputs